version: "3.9"
services:
  mongo:
    container_name: mongo-test
    image: mongo
    ports:
      - "27019:27017" # Host_Port:Container_Port
    command: mongod --quiet --logpath /dev/null --port 27017

  test-backend-ts:
    container_name: test-backend-ts
    build:
      context: "./backend-ts"
      target: test
    ports:
      - "3000:3000"
    volumes:
      - ./backend-ts/src:/home/backend-ts/src
    environment:
      NODE_ENV: '${NODE_ENV}'
      APP_URL: '${APP_URL}'
      APP_PORT: '${APP_PORT}'
      MONGO_CONNECTION_STRING: '${MONGO_CONNECTION_STRING}'
      JWT_SECRET: '${JWT_SECRET}'
      JWT_EXP: '${JWT_EXP}'
      MONGO_HOST: '${MONGO_HOST}'
      MONGO_PORT: '${MONGO_PORT}'
    links:
      - mongo
    depends_on:
      - mongo
    restart: always

