version: "3"
services:
  backend:
    container_name: backend
    build:
      context: "./backend"
      dockerfile: "Dockerfile"
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/home/backend/src
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongo:27018
    links:
      - mongo
    depends_on:
      - mongo
#    restart: always

  frontend:
    container_name: frontend
    build:
      context: "./frontend"
      dockerfile: "Dockerfile"
#      args:
#        REACT_APP_GOOGLE_MAPS_KEY: ${REACT_APP_GOOGLE_MAPS_KEY}
#        REACT_APP_WEATHER_API_KEY: ${REACT_APP_WEATHER_API_KEY}
#        REACT_APP_WEATHER_HOST: ${REACT_APP_WEATHER_HOST}
    ports:
      - "3001:3001"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/home/frontend/src
#    volumes:
#      - '../../../analytics-ui/:/analytics-ui'
#      - '/analytics-ui/node_modules'
#    networks:
#      ia_net:
#        ipv4_address: 172.22.0.9

  mongo:
    container_name: mongo_db
    image: mongo
    ports:
        - "27018:27017"
