version: "3"
services:
  web:
    container_name: node
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/home/node/code/src
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongo:27017
    links:
      - mongo
    depends_on:
      - mongo
#    restart: always

  mongo:
    container_name: mongo
    image: mongo
    ports:
        - "27017:27017"
